---
version: 2.1

executors:
  test_builder_56:
    docker:
      - image: php:5.6
      - image: mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_PASS
        name: mysql.service

  test_builder_70:
    docker:
      - image: php:7.0
      - image: mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: $MYSQL_PASS
        name: mysql.service

jobs:
  php_test_56:
    executor: test_builder_56
    working_directory: ~/woocommerce
    steps:
      - checkout
      - run:
          name: Install system packages php 5.6
          command: |
            apt-get update
            apt-get install -y  git wget curl subversion mysql-client zlib1g-dev/oldstable
      - run:
          name: Enable PHP 5.6 modules
          command: |
            docker-php-ext-install mysqli zip
      - run:
          name: Install composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            HASH="$(wget -q -O - https://composer.github.io/installer.sig)"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } \
                    else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - run:
          name: Install wordpress
          command: |
            cd src
            bin/install-wp-tests.sh wordpress_56 root $MYSQL_PASS mysql.service latest
            cd ..
          environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_PASS
      - run:
          name: Run integration tests
          command: |
            rm -rf packlink-pro-shipping
            mkdir packlink-pro-shipping
            cp -r ./src/* packlink-pro-shipping
            cd packlink-pro-shipping
            composer install
            php vendor/bin/phpunit

  php_test_70:
    executor: test_builder_70
    working_directory: ~/woocommerce
    steps:
      - checkout
      - run:
          name: Install system packages php 7.0
          command: |
            apt-get update
            apt-get install -y  git wget curl subversion mysql-client php7.0-mysql/oldstable php7.0-zip/oldstable zlib1g-dev/oldstable
      - run:
          name: Enable PHP 7.0 modules
          command: |
            docker-php-ext-install mysqli zip
      - run:
          name: Install composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            HASH="$(wget -q -O - https://composer.github.io/installer.sig)"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } \
                    else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - run:
          name: Install wordpress
          command: |
            cd src
            bin/install-wp-tests.sh wordpress_70 root $MYSQL_PASS mysql.service latest
            cd ..
          environment:
            MYSQL_ROOT_PASSWORD: $MYSQL_PASS
      - run:
          name: Run integration tests
          command: |
            rm -rf packlink-pro-shipping
            mkdir packlink-pro-shipping
            cp -r ./src/* packlink-pro-shipping
            cd packlink-pro-shipping
            composer install
            php vendor/bin/phpunit

workflows:
  version: 2.1
  woocommerce_module:
    jobs:
      - php_test_56:
          filters:
            branches:
              only:
                - P5-194
            tags:
              ignore: /.*/

      - php_test_70:
          filters:
            branches:
              only:
                - P5-194
            tags:
              ignore: /.*/
