---
version: 2.1

executors:
  integration_test_builder:
    docker:
      - image: php:7.0
      - image: eu.gcr.io/packlink-tools/packlink-percona:5.6_packlink1
        auth:
          username: _json_key
          password: $GCLOUD_GCR_ADMIN_KEY
        environment:
          MYSQL_ROOT_PASSWORD: root
        name: mysql.service.consul

jobs:
  integration_test:
    executor: integration_test_builder
    working_directory: ~/woocommerce
    steps:
      - checkout
      - run:
          name: Install system packages php 7.0
          command: |
            apt-get update
            apt-get install -y  git wget curl subversion mysql-client php7.0-mysql/oldstable php7.0-zip/oldstable zlib1g-dev/oldstable
      - run:
          name: Enable PHP 7.0 modules
          command: |
            docker-php-ext-install mysqli zip
      - run:
          name: Install composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            HASH="$(wget -q -O - https://composer.github.io/installer.sig)"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === '$HASH') { echo 'Installer verified'; } \
                    else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php --install-dir=/usr/local/bin --filename=composer
      - run:
          name: Install wordpress
          command: |
            cd src
            bin/install-wp-tests.sh wordpress_70 root root mysql.service.consul latest
            cd ..
      - run:
          name: Run integration tests
          command: |
            rm -rf packlink-pro-shipping
            mkdir packlink-pro-shipping
            cp -r ./src/* packlink-pro-shipping
            cd packlink-pro-shipping
            composer install
            php vendor/bin/phpunit

workflows:
  version: 2.1
  woocommerce_module: 
    jobs:
      - integration_test:
          filters:
            branches:
              only:
                - P5-194
            tags:
              ignore: /.*/

